template: true
valuesFilePath: ./values.yml

resources:
  {{ range $i, $e := until 5 }}
  - name: monitor_cron_trigger{{$i}}
    type: CronTrigger
    configuration:
      interval: '0 12 * * *' # every 12 noon
  {{ end }}

pipelines:
  - name: testcron
    steps:
      - name: basic
        type: Bash
        configuration:
          runtime:
            type: host
          inputResources:
          {{ range $i, $e := until 5 }}
            - name: monitor_cron_trigger{{$i}}
          {{ end }}
        execution:
          onExecute:
            - echo hi
